const actions = [
  'RESET_GRAPH',
  'SHOW_SPLASH',
  'HIDE_SPLASH',
  'LOAD_DONE',
  'DO_LAYOUT',
  'LAYOUT_DONE',
  'REDRAW',
  'CLEAR',
  'TOGGLE_CONTROLS',
  'SHOW_LEGEND_CONTROLS',
  'SHOW_GRAPH_CONTROLS',
  'ADD_NODE',
  'ADD_NOTE',
  'REMOVE_ELEMENT',
  'SELECT_ELEMENT',
  'DESELECT_ELEMENT',
  'ADD_EDGE',
  'SET_IN_HANDLE',
  'CLEAR_IN_HANDLE',
  'SET_OUT_HANDLE',
  'CLEAR_OUT_HANDLE',
  'START_CONNECTING',
  'END_CONNECTING',
  'START_DRAGGING_NOTE',
  'END_DRAGGING_NOTE',
  'SET_DISRUPTIONS',
  'SET_ELEMENT_ATTRIBUTE',
  'SET_GRAPH_ATTRIBUTE',
  'EXPORT_JSON',
  'EXPORT_PNG',
  'SET_STATE',
  'ADD_STATE',
  'REMOVE_STATE',
  'SET_STATE_NAME',
  'SET_COLOR_LABEL'
];

export default actions.reduce((prev, cur) => {
  prev[cur] = cur;
  return prev;
}, {});
